# Generated by Django 4.2.11 on 2024-04-27 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hwapp2', '0005_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producthwapp4',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hwapp2.product')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            bases=('hwapp2.product',),
        ),
    ]
